coverage:
  status:
    project:
      default:
        target: auto  # Accept current coverage as target (or set a fixed number)
        threshold: 0.5  # Allow small drops
        flags: []
        paths: []

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: true

comment: false  # Disable bot comments if not needed

coverage:
  range: 60..80  # Yellow for 60–79.9%, Green from 80% upward

ignore:
  - "**/generated/**"
  - "**/config/**"
  - "**/ChatMessage.java"
  - "**/PBImplA.java"
  - "**/TracerImpl.java"
